image: node:latest

stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync dist s3://ssungbti.yourssu.com
  only:
    - master
