image: node:latest

stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist

deploy:
  image: amazon/aws-cli:latest
  stage: deploy
  script:
    - aws s3 sync dist s3://$S3_BUCKET_NAME
  only:
    - master
