image: node:latest

pages:
  stage: deploy
  script:
    - yarn
    - yarn build
    - mv dist public
  variables:
    PUBLIC_PATH: https://yourssu.gitlab.io/ssungbti
    BASE_NAME: /ssungbti
  artifacts:
    paths:
      - public
  only:
    - master
