name: Build Test

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependency
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
